#!/bin/bash

convert ../../web/photo_orig.png -resize "36x36!" res/drawable-ldpi/icon.png
convert ../../web/photo_orig.png -resize "48x48!" res/drawable-mdpi/icon.png
convert ../../web/photo_orig.png -resize "72x72!" res/drawable-hdpi/icon.png
