#!/bin/bash

convert photo_orig_2.png -resize '120x120!' icon120.png
convert photo_orig_2.png -resize '180x180!' icon180.png
convert photo_orig_2.png -resize '152x152!' icon152.png
convert photo_orig_2.png -resize '512x512!' icon512.png
convert photo_orig_2.png -resize '120x120!' icon120.png
convert photo_orig_2.png -resize '114x114!' icon114.png
convert photo_orig_2.png -resize '72x72!' icon72.png
convert photo_orig_2.png -resize '144x144!' icon144.png
convert photo_orig_2.png -resize '57x57!' icon57.png
convert photo_orig_2.png -resize '87x87!' icon87.png
convert photo_orig_2.png -resize '80x80!' icon80.png
convert photo_orig_2.png -resize '58x58!' icon58.png
convert photo_orig_2.png -resize '29x29!' icon29.png
convert photo_orig_2.png -resize '40x40!' icon40.png
convert photo_orig_2.png -resize '60x60!' icon60.png
convert photo_orig_2.png -resize '76x76!' icon76.png
